/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Rate: typeof import('./../src/components/rate/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZInput: typeof import('./../src/components/z-input/index.vue')['default']
    ZModel: typeof import('./../src/components/z-model/index.vue')['default']
    ZPopup: typeof import('./../src/components/z-popup/index.vue')['default']
    ZProgress: typeof import('./../src/components/z-progress/index.vue')['default']
  }
}
